permalink: /:year/:month/:day/:title.html
paginate: 10

# 作者信息
author:
  name: jaky.wang
  email: wj940096538@163.com
  github: http://github.com/littlePang

# 站点信息
title: 小胖的博客
description: My personal blog
url: http://littlepang.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
#/public/img/deer3.png
gavatar: /assets/picture/headPicture.jpg
favicon: /assets/picture/headPicture.jpg

# google analytics 设置
ga:
  id: UA-54262064-1
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: stuff

# 首页除了最新文章外显示分类
cates:
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
